* Mitchell Gravity Set                                             :TOC_5_gh:
  - [[#synopsis][Synopsis]]
  - [[#background][Background]]
    - [[#motivation][Motivation]]
  - [[#why-this-is-just-a-library][Why this is just a library]]
  - [[#contributing][Contributing]]
  - [[#debugging][Debugging]]

** Synopsis
   This library generates the Gravity Set,
** Background
   Please see:

   https://mitchell-gravity-set.quora.com/

   for the mathematical background behind MGS.

*** Motivation
    The original MGS was implemented as a 2D gravity field.
    As well, at the time, the computing power of the computers
    at the time were limited, and generating a 3D field would've
    required a lot more time.

    Today, multicore CPUs are common, and so I've decided
    to implement this solely as 3D. We are entering new
    territory here, as I do not know what to expect. But
    it makes more sense anyway, since real gravity operates
    in 3D space, in the classical Newtonian sense.

    Besides, today we have very impressive 3D fractals rendered
    by others, and I am not willing to be "left out" of the
    fun! This will also be a serious chance to make use of the
    OpenGL library for rendering the results.

** TODO Why this is just a library
** TODO Contributing
** TODO Debugging
